language: ruby
cache: bundler

rvm:
  - 2.1.2

before_install:
  - gem install bundler

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - pghalliday@gmail.com
    on_failure: change
    on_success: never
