#!/usr/bin/env ruby

require 'rubygems'
require 'commander/import'
require 'formatron/version'
require 'formatron/credentials'
require 'formatron/bootstrap'

program :version, Formatron::VERSION
program :description, 'Quickly deploy AWS CloudFormation ' \
                      'stacks backed by a Chef Server'

command :deploy do |c|
  c.syntax = 'formatron deploy, [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |_args, _options|
    # Do something or c.when_called Formatron::Commands::Deploy,
  end
end

command :credentials do |c|
  c.syntax = 'formatron credentials, [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |_args, _options|
    credentials = ask 'Credentials file? ' do |q|
      q.default = if File.file?('Formatronfile')
                    File.join(Dir.pwd, '.formatron', 'credentials.json')
                  else
                    File.join(Dir.home, '.formatron', 'credentials.json')
                  end
    end
    region = choose(
      "Region:\n",
      'us-east-1',
      'us-west-2',
      'us-west-1',
      'eu-west-1',
      'eu-central-1',
      'ap-southeast-1',
      'ap-southeast-2',
      'ap-northeast-1',
      'sa-east-1'
    )
    access_key_id = ask 'Access Key ID? '
    secret_access_key = password 'Secret Access Key? '
    Formatron::Credentials.generate(
      credentials,
      region,
      access_key_id,
      secret_access_key
    )
  end
end

command :bootstrap do |c|
  c.syntax = 'formatron bootstrap, [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |_args, _options|
    configuration = ask 'Directory? ' do |q|
      q.default = '.'
    end
    name = ask 'Name? ' do |q|
      q.default = File.basename File.expand_path(configuration)
    end
    hosted_zone_id = ask 'Hosted Zone ID? '
    Formatron::Bootstrap.generate(
      configuration,
      name,
      hosted_zone_id
    )
  end
end

command :instance do |c|
  c.syntax = 'formatron instance [options]'
  c.summary = ''
  c.description = ''
  c.example 'description', 'command example'
  c.option '--some-switch', 'Some switch that does something'
  c.action do |_args, _options|
    configuration = ask 'Directory? ' do |q|
      q.default = '.'
    end
    name = ask 'Name? ' do |q|
      q.default = File.basename configuration
    end
    bootstrap_configuration = ask 'Bootstrap configuration? '
    Formatron::Instance.generate(
      configuration,
      name,
      bootstrap_configuration
    )
  end
end
